---
# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

APPLY_FIXES: none  # all, none, or list of linter keys
DEFAULT_BRANCH: main  # Usually master or main
ENABLE:
  - TYPESCRIPT
ENABLE_LINTERS:  # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
  - REPOSITORY_GITLEAKS
  - REPOSITORY_TRIVY
  - REPOSITORY_GIT_DIFF
  - DOCKERFILE_HADOLINT
  - TYPESCRIPT_ES
  - JSON_NPM_PACKAGE_JSON_LINT
DISABLE:
  - CLOUDFORMATION
  # - COPYPASTE  # Uncomment to disable checks of abusive copy-pastes
  - EDITORCONFIG
  - MARKDOWN
  # - REPOSITORY
  - SPELL  # Uncomment to disable checks of spelling mistakes
  - YAML
  - TEKTON
  - SPELL_LYCHEE
  - PYTHON
DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  # - JSON_PRETTIER
  # - JSON_JSONLINT
  # - DOCKERFILE_HADOLINT
  - REPOSITORY_CHECKOV
  - REPOSITORY_DEVSKIM
  - REPOSITORY_DUSTILOCK
  - REPOSITORY_TRIVY
  - REPOSITORY_SYFT
  - REPOSITORY_KICS
  - REPOSITORY_GRYPE
  - REPOSITORY_TRUFFLEHOG
  - REPOSITORY_TRIVY_SBOM
  # - RST_RST_LINT
  - RST_RSTCHECK
  - TERRAFORM_TERRAGRUNT
  - TERRAFORM_TERRASCAN
  - TERRAFORM_KICS
  - PYTHON_MYPY
  - PYTHON_PYRIGHT
  - PYTHON_PYLINT
  - BASH_SHELLCHECK  # too slow
  - BASH_SHFMT       # too slow
  - COPYPASTE_JSCPD  # too slow
  - JAVASCRIPT_ES
  - JSON_PRETTIER
IGNORE_GITIGNORED_FILES: true
FILTER_REGEX_EXCLUDE: (\.automation/test|\.automation/generated|\.github/workflows|\.venv/|\.direnv/|\.mypy_cache/|docs/javascripts|docs/overrides|docs/json-schemas|flavors|clj-kondo|TEMPLATES|tests)
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: (\.vscode/)
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: (templates/\.mega-linter\.yml)
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: (templates/\.mega-linter\.yml|mkdocs\.yml)
YAML_V8R_FILTER_REGEX_EXCLUDE: (descriptors|templates/\.mega-linter\.yml|\.codecov\.yml)
BASH_FILTER_REGEX_EXCLUDE: (lib)
MARKDOWN_FILTER_REGEX_EXCLUDE: (license\.md)
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
SPELL_MISSPELL_FILTER_REGEX_EXCLUDE: (\.automation/generated|docs/descriptors)
DOCKERFILE_HADOLINT_ARGUMENTS: --ignore DL3003 --ignore DL3007 --ignore DL3013 --ignore DL3016 --ignore DL3018 --ignore DL3028 --ignore DL4001 --ignore DL4006 --ignore
  SC2015 --ignore SC2016 --ignore SC2039 --ignore SC2086 --ignore SC1091
REPOSITORY_DEVSKIM_DISABLE_ERRORS: true
REPOSITORY_DEVSKIM_ARGUMENTS: --severity critical,important --ignore-globs **/.git/**,**/bin/**,.mypy_cache/**,**/tests/**,**/README.md
REPOSITORY_DEVSKIM_DISABLE_ERRORS_IF_LESS_THAN: 10
REPOSITORY_TRIVY_DISABLE_ERRORS: true
REPOSITORY_TRIVY_ARGUMENTS: --security-checks vuln,config,secret --vuln-type os,library --ignore-unfixed  --ignorefile .trivyignore.yaml --skip-dirs .direnv --skip-dirs .venv --skip-dirs megalinter-reports --skip-files pip.conf --skip-files Pipfile
REPOSITORY_TRIVY_DISABLE_ERRORS_IF_LESS_THAN: 15
REPOSITORY_GITLEAKS_DISABLE_ERRORS: false
REPOSITORY_GITLEAKS_ARGUMENTS: --no-git
REPOSITORY_SECRETLINT_DISABLE_ERRORS: false
BASH_SHELLCHECK_DISABLE_ERRORS: true
PYTHON_BANDIT_DISABLE_ERRORS: true
PYTHON_MYPY_DISABLE_ERRORS: true
PYTHON_PYLINT_DISABLE_ERRORS: true
PYTHON_PYRIGHT_DISABLE_ERRORS: true
TYPESCRIPT_ES_CONFIG_FILE: eslint.config.mjs
EXCLUDED_DIRECTORIES: [".github", ".gitlab-ci", "node_modules", ".venv", ".direnv", ".mypy_cache"]
SHOW_ELAPSED_TIME: true
JSON_REPORTER: true
SARIF_REPORTER: true
FILEIO_REPORTER: false
VALIDATE_ALL_CODEBASE: false
FLAVOR_SUGGESTIONS: false
SHOW_SKIPPED_LINTERS: false
PRE_COMMANDS:
  - command: echo "This is Mega-Linter PRE_COMMAND on own Mega-Linter ! :)"
    cwd: root
  - command: |-
      echo $(ls -lah .gitignore | sed 's/\s\+/ /g' | cut -d ' ' -f3,4 | sed 's/ /\:/') > perms.txt
    cwd: "workspace"
POST_COMMANDS:
  - command: echo "This is Mega-Linter POST_COMMAND on own Mega-Linter ! :)"
    cwd: workspace
  - command: |-
      find . -user root -group root -exec chown $(cat perms.txt) {} \;
      rm perms.txt
    cwd: "workspace"
